version: 0.0
os: linux
files:
  - source: /source_code.zip
    destination: /var/lib/deploy

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
