version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Running pre-build checks...
      - python -m flake8 # Example linting command
  build:
    commands:
      - echo Running tests...
      - export PYTHONPATH=$PYTHONPATH:/codebuild/output/src1454388845/src
      - pytest tests/*.py --maxfail=3 --disable-warnings -v
      - mkdir testfile

artifacts:
  files:
    - '**/*' 
