version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing necessary tools..."
      - apt-get update -y
      - apt-get install -y curl zip  # Install required tools
      - echo "Installing Azure CLI..."
      - curl -sL https://aka.ms/InstallAzureCLIDeb | bash  # Install Azure CLI
      - az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_SECRET --tenant $AZURE_TENANT_ID  # Authenticate with Azure

  pre_build:
    commands:
      - echo "Verifying the source directory contents..."
      - ls -la $CODEBUILD_SRC_DIR  # Verify source code is downloaded correctly
      - mkdir -p ./build
      - echo "Copying files to build directory..."
      - find $CODEBUILD_SRC_DIR -mindepth 1 -maxdepth 1 ! -name "build" -exec cp -r {} ./build/ \;
      - echo "Files in build directory:"
      - ls -la ./build/  # Verify if files are copied to build

  build:
    commands:
      - echo "Deploying to Azure App Service..."
      - az webapp deploy --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_APP_SERVICE_NAME --src-path ./build/   # Deploy the zip file to Azure

artifacts:
  files:
    - '**/*'
