version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing necessary tools..."
      - apt-get update -y
      - apt-get install -y curl zip  # Install required tools
      - echo "Installing Azure CLI..."
      - curl -sL https://aka.ms/InstallAzureCLIDeb | bash  # Install Azure CLI
      - az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_SECRET --tenant $AZURE_TENANT_ID  # Authenticate with Azure

  pre_build:
    commands:
      - echo "Preparing source files for deployment..."
      - mkdir -p ./build
      - cp -r $CODEBUILD_SRC_DIR/* ./build/  # Copy the source code from the default directory to the build folder

  build:
    commands:
      - echo "Creating deployment package..."
      - zip -r build.zip ./build/  # Zip all files in the build directory
      - echo "Verifying the deployment package..."
      - ls -la build.zip  # Verify the zip file is created
      - echo "Deploying to Azure App Service..."
      - az webapp deploy --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_APP_SERVICE_NAME --src-path build.zip --type zip  # Deploy the zip file to Azure

artifacts:
  files:
    - '**/*'
