version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - apt-get update -y
      - apt-get install -y curl zip unzip  # Install necessary tools
      - curl -sL https://aka.ms/InstallAzureCLIDeb | bash  # Install Azure CLI
      - az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_SECRET --tenant $AZURE_TENANT_ID

  pre_build:
    commands:
      - echo "Downloading source files from S3..."
      - aws s3 cp s3://azurebucket-01/aws-to-azure-build/BuildArtif/ ./source/ --recursive  # Download all files
      - ls -la ./source/  # Verify that files have been downloaded

  build:
    commands:
      - echo "Verifying downloaded source files..."
      - find ./source/ -type f -exec file {} \;  # Display file types to ensure content integrity
      - echo "Creating deployment package..."
      - zip -r build.zip ./source/  # Zip all files from the 'source' directory
      - ls -la  # Verify the zip file is created
      - echo "Deploying build.zip to Azure App Service..."
      - az webapp deploy --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_APP_SERVICE_NAME --src-path build.zip --type zip

artifacts:
  files:
    - '**/*'
