version: 0.2

env:
  variables:
    S3_BUCKET: "s3://mylinuxbucket01/"  # Replace with your bucket name

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo "Running pre-build tests"
      - python -m unittest discover tests

  build:
    commands:
      - echo "Zipping the entire source code..."
      # - mkdir -p build
      - zip -r source_code.zip *

artifacts:
  files:
    - 'source_code.zip'
  discard-paths: yes
