version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # Example runtime (ensure it matches your needs)
    commands:
      - yum update -y  # Update package manager for Amazon Linux
      - yum install -y curl --skip-broken # Install curl
      - curl -sL https://aka.ms/InstallAzureCLIDeb | bash  # Install Azure CLI
      - az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_SECRET --tenant $AZURE_TENANT_ID

  build:
    commands:
      - az webapp deploy --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_APP_SERVICE_NAME --src-path build.zip

artifacts:
  files:
    - '**/*'
