version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # Example runtime (ensure it matches your needs)
    commands:
      - apt-get update -y
      - apt-get install -y curl zip  # Install curl and zip
      - curl -sL https://aka.ms/InstallAzureCLIDeb | bash  # Install Azure CLI
      - az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_SECRET --tenant $AZURE_TENANT_ID

  pre_build:
    commands:
      - echo "Downloading source files from S3..."
      - aws s3 cp s3://azurebucket-01/aws-to-azure-build/SourceArti/ ./source/ --recursive  # Download all files from the S3 bucket
      - ls -la ./source/  # Verify that files have been downloaded

  build:
    commands:
      - echo "Preparing files for deployment..."
      - mkdir build  # Create a build directory
      - cp -r ./source/* build/  # Copy downloaded files into the build directory
      - echo "Creating build.zip..."
      - zip -r build.zip build/  # Package all files in the 'build' directory into a zip file
      - ls -la  # Verify the zip file is created
      - echo "Deploying build.zip to Azure App Service..."
      - az webapp deploy --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_APP_SERVICE_NAME --src-path build.zip --type zip

artifacts:
  files:
    - '**/*'
