version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # Example runtime (ensure it matches your needs)
    commands:
      - apt-get update -y
      - apt-get install -y curl zip  # Install curl and zip
      - curl -sL https://aka.ms/InstallAzureCLIDeb | bash  # Install Azure CLI
      - az login --service-principal --username $AZURE_CLIENT_ID --password $AZURE_SECRET --tenant $AZURE_TENANT_ID

pre_build:
  commands:
    - echo "Checking current directory and contents..."
    - pwd  # Print the current working directory
    - ls -la  # List all files and directories

  build:
    commands:
      - echo "Preparing source files for deployment..."
      - mkdir build  # Create a build directory
      - cp -r ./source/* build/  # Adjust './source/*' to point to your source files
      - echo "Creating build.zip for deployment..."
      - zip -r build.zip build/  # Package all files in the 'build/' directory into a zip file
      - ls -la  # Verify the zip file is created
      - echo "Deploying build.zip to Azure App Service..."
      - az webapp deploy --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_APP_SERVICE_NAME --src-path build.zip --type zip

artifacts:
  files:
    - '**/*'
